#!/bin/bash
#=================================================================================#
#        MagenX e-commerce stack for Magento 2                                    #
#        Copyright (C) 2013-present admin@magenx.com                              #
#        All rights reserved.                                                     #
#=================================================================================#

INSTANCE_LOCAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

## installation
apt-mark hold ${EXCLUDE_PACKAGES_DEB}
apt-get update
apt-get -qqy install ${EXTRA_PACKAGES_DEB}
pip3 install git-remote-codecommit

## create user
useradd -d /home/${BRAND} -s /bin/bash ${BRAND}
## create root php user
useradd -M -s /sbin/nologin -d /home/${BRAND} ${PHP_USER}
usermod -g ${PHP_USER} ${BRAND}

mkdir -p ${WEB_ROOT_PATH}
chmod 711 /home/${BRAND}
mkdir -p /home/${BRAND}/{.config,.cache,.local,.composer}
chown -R ${BRAND}:${PHP_USER} ${WEB_ROOT_PATH} /home/${BRAND}/{.config,.cache,.local,.composer}
chmod 2770 ${WEB_ROOT_PATH}
setfacl -R -m u:${BRAND}:rwX,g:${PHP_USER}:r-X,o::-,d:u:${BRAND}:rwX,d:g:${PHP_USER}:r-X,d:o::- ${WEB_ROOT_PATH}
cd ${WEB_ROOT_PATH}
su ${BRAND} -s /bin/bash -c "git clone -b main ${CODECOMMIT_APP_REPO} ."
echo "${EFS_DNS_TARGET}:/%{ if "${INSTANCE_NAME}" != "staging" }production%{ else }staging%{ endif }/var ${WEB_ROOT_PATH}/var nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab
echo "${EFS_DNS_TARGET}:/%{ if "${INSTANCE_NAME}" != "staging" }production%{ else }staging%{ endif }/pub/media ${WEB_ROOT_PATH}/pub/media nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab
su ${BRAND} -s /bin/bash -c "mkdir -p {pub/media,var}"
mount -a

if [ $(stat -f -L -c %T ${WEB_ROOT_PATH}/pub/media) != "nfs" ]; then
mkdir -p /mnt/efs
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${EFS_DNS_TARGET}:/ /mnt/efs
mkdir -p /mnt/efs/{production,staging,build}/{var,pub/media}
chown -R ${BRAND}:${PHP_USER} /mnt/efs/
find /mnt/efs -type d -exec chmod 2770 {} \;
umount /mnt/efs
mount -a
fi

chmod 2770 pub/media var
chmod +x bin/magento

## install nginx
curl -s https://nginx.org/keys/nginx_signing.key | gpg --dearmor > /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/debian `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list
echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" > /etc/apt/preferences.d/99nginx

## install php + phpmyadmin
wget -qO /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

%{ if "${INSTANCE_NAME}" == "admin" }
debconf-set-selections <<< "phpmyadmin phpmyadmin/internal/skip-preseed boolean true"
debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect"
debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean false"
%{ endif }

for repository in nginx php; do apt-get -qq update -o Dir::Etc::sourcelist="sources.list.d/$${repository}.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"; done
apt-get -qqy install %{ if "${INSTANCE_NAME}" == "admin" }phpmyadmin%{ endif } nginx composer php-pear php${PHP_VERSION} %{ for PHP_PKG in split(" ", "${PHP_PACKAGES_DEB}") ~} php${PHP_VERSION}-${PHP_PKG} %{ endfor }

cat > /etc/sysctl.conf <<END
fs.file-max = 1000000
fs.inotify.max_user_watches = 1000000
vm.swappiness = 5
net.ipv4.ip_forward = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.sysrq = 0
kernel.core_uses_pid = 1
kernel.msgmnb = 65535
kernel.msgmax = 65535
kernel.shmmax = 68719476736
kernel.shmall = 4294967296
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mem = 8388608 8388608 8388608
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 65535 8388608
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_challenge_ack_limit = 1073741823
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 15
net.ipv4.tcp_max_orphans = 262144
net.ipv4.tcp_max_syn_backlog = 262144
net.ipv4.tcp_max_tw_buckets = 400000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_sack = 1
net.ipv4.route.flush = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 8388608
net.core.wmem_default = 8388608
net.core.netdev_max_backlog = 262144
net.core.somaxconn = 65535
END

sysctl -q -p

cat > ${PHP_OPCACHE_INI} <<END
zend_extension=opcache.so
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 512
opcache.interned_strings_buffer = 4
opcache.max_accelerated_files = 60000
opcache.max_wasted_percentage = 5
opcache.use_cwd = 1
opcache.validate_timestamps = 0
;opcache.revalidate_freq = 2
;opcache.validate_permission = 1
opcache.validate_root = 1
opcache.file_update_protection = 2
opcache.revalidate_path = 0
opcache.save_comments = 1
opcache.load_comments = 1
opcache.fast_shutdown = 1
opcache.enable_file_override = 0
opcache.optimization_level = 0xffffffff
opcache.inherited_hack = 1
opcache.blacklist_filename=/etc/opcache-default.blacklist
opcache.max_file_size = 0
opcache.consistency_checks = 0
opcache.force_restart_timeout = 60
opcache.error_log = "/var/log/php-fpm/opcache.log"
opcache.log_verbosity_level = 1
opcache.preferred_memory_model = ""
opcache.protect_memory = 0
;opcache.mmap_base = ""
END

cp ${PHP_INI} ${PHP_INI}.BACK
sed -i 's/^\(max_execution_time = \)[0-9]*/\17200/' ${PHP_INI}
sed -i 's/^\(max_input_time = \)[0-9]*/\17200/' ${PHP_INI}
sed -i 's/^\(memory_limit = \)[0-9]*M/\1%{ if "${INSTANCE_NAME}" == "admin" }2048M%{ else }756M%{ endif }/' ${PHP_INI}
sed -i 's/^\(post_max_size = \)[0-9]*M/\164M/' ${PHP_INI}
sed -i 's/^\(upload_max_filesize = \)[0-9]*M/\132M/' ${PHP_INI}
sed -i 's/expose_php = On/expose_php = Off/' ${PHP_INI}
sed -i 's/;realpath_cache_size =.*/realpath_cache_size = 10M/' ${PHP_INI}
sed -i 's/;realpath_cache_ttl =.*/realpath_cache_ttl = 86400/' ${PHP_INI}
sed -i 's/short_open_tag = Off/short_open_tag = On/' ${PHP_INI}
sed -i 's/;max_input_vars =.*/max_input_vars = 50000/' ${PHP_INI}
sed -i 's/session.gc_maxlifetime = 1440/session.gc_maxlifetime = 28800/' ${PHP_INI}
sed -i 's/mysql.allow_persistent = On/mysql.allow_persistent = Off/' ${PHP_INI}
sed -i 's/mysqli.allow_persistent = On/mysqli.allow_persistent = Off/' ${PHP_INI}
sed -i 's/pm = dynamic/pm = ondemand/' ${PHP_FPM_POOL}
sed -i 's/;pm.max_requests = 500/pm.max_requests = 10000/' ${PHP_FPM_POOL}
sed -i 's/^\(pm.max_children = \)[0-9]*/\1100/' ${PHP_FPM_POOL}

sed -i "s/\[www\]/\[${BRAND}\]/" ${PHP_FPM_POOL}
sed -i "s/^user =.*/user = ${PHP_USER}/" ${PHP_FPM_POOL}
sed -i "s/^group =.*/group = ${PHP_USER}/" ${PHP_FPM_POOL}
sed -ri "s/;?listen.owner =.*/listen.owner = ${BRAND}/" ${PHP_FPM_POOL}
sed -ri "s/;?listen.group =.*/listen.group = ${PHP_USER}/" ${PHP_FPM_POOL}
sed -ri "s/;?listen.mode = 0660/listen.mode = 0660/" ${PHP_FPM_POOL}
sed -ri "s/;?listen.allowed_clients =.*/listen.allowed_clients = 127.0.0.1/" ${PHP_FPM_POOL}
sed -i '/sendmail_path/,$d' ${PHP_FPM_POOL}
sed -i '/PHPSESSID/d' ${PHP_INI}
sed -i "s,.*date.timezone.*,date.timezone = ${TIMEZONE}," ${PHP_INI}

cat >> ${PHP_FPM_POOL} <<END
;;
;; Custom pool settings
php_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[error_log] = "${WEB_ROOT_PATH}/var/log/php-fpm-error.log"
php_admin_value[default_charset] = UTF-8
php_admin_value[memory_limit] = %{ if "${INSTANCE_NAME}" == "admin" }2048M%{ else }756M%{ endif }
php_admin_value[date.timezone] = ${TIMEZONE}
END

echo "${WEB_ROOT_PATH}/app/etc/env.php" >> /etc/opcache-default.blacklist
echo "${WEB_ROOT_PATH}/app/etc/config.php" >> /etc/opcache-default.blacklist

cd /etc/nginx
git init
git remote add origin ${CODECOMMIT_SERVICES_REPO}
git fetch
git reset --hard origin/nginx_${INSTANCE_NAME}
git checkout -t origin/nginx_${INSTANCE_NAME}

ln -s /etc/nginx/sites-available/magento.conf /etc/nginx/sites-enabled/magento.conf

sed -i "s/user  nginx;/user  ${BRAND};/" /etc/nginx/nginx.conf
sed -i "s/CIDR/${CIDR}/" /etc/nginx/nginx.conf
sed -i "s/INSTANCE_LOCAL_IP/$${INSTANCE_LOCAL_IP}/" /etc/nginx/sites-available/magento.conf
sed -i "s/example.com/%{ if "${INSTANCE_NAME}" != "staging" }${DOMAIN}%{ else }${STAGING_DOMAIN}%{ endif }/g" /etc/nginx/sites-available/magento.conf
sed -i "s/example.com/%{ if "${INSTANCE_NAME}" != "staging" }${DOMAIN}%{ else }${STAGING_DOMAIN}%{ endif }/g" /etc/nginx/nginx.conf
sed -i "s,/var/www/html,${WEB_ROOT_PATH},g" /etc/nginx/conf.d/maps.conf

sed -i "s/PROFILER_PLACEHOLDER/${PROFILER}/" /etc/nginx/conf.d/maps.conf

%{ if "${INSTANCE_NAME}" == "admin" }
sed -i "s/.*blowfish_secret.*/\$cfg['blowfish_secret'] = '${BLOWFISH}';/" /var/lib/phpmyadmin/blowfish_secret.inc.php
sed -i "s/PHPMYADMIN_PLACEHOLDER/${MYSQL_PATH}/g" /etc/nginx/conf.d/phpmyadmin.conf
%{ endif }

systemctl daemon-reload
systemctl restart nginx.service
systemctl restart php*fpm.service

hostnamectl set-hostname server.${DOMAIN} --static
timedatectl set-timezone ${TIMEZONE}

cd /usr/local/src
wget https://s3.${AWS_DEFAULT_REGION}.amazonaws.com/amazon-ssm-${AWS_DEFAULT_REGION}/latest/debian_arm64/amazon-ssm-agent.deb
dpkg -i amazon-ssm-agent.deb
systemctl enable amazon-ssm-agent

wget https://s3.${AWS_DEFAULT_REGION}.amazonaws.com/amazoncloudwatch-agent-${AWS_DEFAULT_REGION}/debian/arm64/latest/amazon-cloudwatch-agent.deb
dpkg -i amazon-cloudwatch-agent.deb
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:amazon-cloudwatch-agent-${INSTANCE_NAME}.json
