#!/bin/bash
#=================================================================================#
#        MagenX e-commerce stack for Magento 2                                    #
#        Copyright (C) 2013-present admin@magenx.com                              #
#        All rights reserved.                                                     #
#=================================================================================#

AWSTOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
INSTANCE_LOCAL_IP=$(curl -s -H "X-aws-ec2-metadata-token: $${AWSTOKEN}" http://169.254.169.254/latest/meta-data/local-ipv4)
INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $${AWSTOKEN}" http://169.254.169.254/latest/meta-data/instance-id)
INSTANCE_TYPE=$(curl -s -H "X-aws-ec2-metadata-token: $${AWSTOKEN}" http://169.254.169.254/latest/meta-data/instance-type)

_TIMER_USER_DATA_START="$(date +%T)"

if [ $(stat -f -L -c %T ${WEB_ROOT_PATH}/pub/media) != "nfs" ]; then
mkdir -p /mnt/efs
mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 ${EFS_DNS_TARGET}:/ /mnt/efs
mkdir -p /mnt/efs/data/{var,pub/media}
chown -R ${BRAND}:${PHP_USER} /mnt/efs/
find /mnt/efs -type d -exec chmod 2770 {} \;
umount /mnt/efs
mount -a
fi

cd ${WEB_ROOT_PATH}
su ${BRAND} -s /bin/bash -c "git init -b main"
su ${BRAND} -s /bin/bash -c "git remote add origin ${CODECOMMIT_APP_REPO}"
su ${BRAND} -s /bin/bash -c "git fetch origin main"
su ${BRAND} -s /bin/bash -c "git reset origin/main --hard"

sed -i "s/INSTANCE_LOCAL_IP/$${INSTANCE_LOCAL_IP}/" /etc/nginx/sites-available/magento.conf
systemctl restart nginx

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:amazon-cloudwatch-agent-${INSTANCE_NAME}.json

chmod 750 /usr/bin/aws

cat > /tmp/timer_user_data_log <<END
Instance: ${INSTANCE_NAME} $${INSTANCE_ID} $${INSTANCE_TYPE}
Region: ${AWS_DEFAULT_REGION}
Brand: ${BRAND}
Uptime since:  $(uptime -s)
END

/bin/systemctl status nginx.service php*fpm.service >> /tmp/timer_user_data_log
ss -tunlp >> /tmp/timer_user_data_log

aws sns publish \
    --region ${AWS_DEFAULT_REGION} \
    --topic-arn ${SNS_TOPIC_ARN} \
    --subject "Timer for user_data: ${BRAND} at ${AWS_DEFAULT_REGION} ${INSTANCE_NAME} $${INSTANCE_ID}" \
    --message file:///tmp/timer_user_data_log
    
    
iptables -A OUTPUT -m owner --uid-owner ${PHP_USER} -d 169.254.169.254 -j DROP
