#!/bin/bash
#=================================================================================#
#        MagenX e-commerce stack for Magento 2                                    #
#        Copyright (C) 2013-present admin@magenx.com                              #
#        All rights reserved.                                                     #
#=================================================================================#


INSTANCE_LOCAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

## system installation
apt-get -y install software-properties-common
apt-get update
apt-get -y install ${EXTRA_PACKAGES_DEB}

pip3 install git-remote-codecommit

## install nginx
echo "deb http://nginx.org/packages/mainline/ubuntu `lsb_release -cs` nginx" > /etc/apt/sources.list.d/nginx.list
curl -fsSL https://nginx.org/keys/nginx_signing.key | apt-key add -
apt-get update
apt-get -y install nginx

## install varnish
#curl -s https://packagecloud.io/install/repositories/varnishcache/varnish65/script.deb.sh | bash
#apt-get update
apt-get -y install varnish

systemctl stop nginx varnish

cd /etc/varnish
git init
git remote add origin ${CODECOMMIT_SERVICES_REPO}
git fetch
git reset --hard origin/varnish
git checkout -t origin/varnish

sed -i "s/INSTANCE_LOCAL_IP/$${INSTANCE_LOCAL_IP}/" /etc/varnish/default.vcl
sed -i "s/INSTANCE_LOCAL_IP/$${INSTANCE_LOCAL_IP}/" /etc/varnish/varnish.params

uuidgen > /etc/varnish/secret

cd /etc/systemd/system/
git init
git remote add origin ${CODECOMMIT_SERVICES_REPO}
git fetch
git reset --hard origin/systemd_proxy
git checkout -t origin/systemd_proxy

cd /etc/nginx
git init
git remote add origin ${CODECOMMIT_SERVICES_REPO}
git fetch
git reset --hard origin/nginx_proxy
git checkout -t origin/nginx_proxy

sed -i "s/CIDR/${CIDR}/" /etc/nginx/nginx.conf
sed -i "s/RESOLVER/${RESOLVER}/" /etc/nginx/nginx.conf
sed -i "s/INSTANCE_LOCAL_IP/$${INSTANCE_LOCAL_IP}/" /etc/nginx/nginx.conf
sed -i "s/DOMAIN/${DOMAIN} ${STAGING_DOMAIN}/" /etc/nginx/nginx.conf
sed -i "s/ALB_DNS_NAME/${ALB_DNS_NAME}/" /etc/nginx/nginx.conf
sed -i "s/MAGENX_HEADER/${MAGENX_HEADER}/" /etc/nginx/nginx.conf

systemctl daemon-reload
systemctl enable varnish
systemctl restart nginx varnish

## install CloudWatch agent with config from SSM Parameter store
cd /usr/local/src
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb
dpkg -i -E ./amazon-cloudwatch-agent.deb

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:amazon-cloudwatch-agent-${INSTANCE_NAME}.json
