version: 0.2

env:
  shell: bash
    
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: ${PHP_VERSION}
    commands:
      - echo "Configuration start at $(date)"
      - php -m
      - php -v
      - echo "Configuration end at $(date)"
  build:
    on-failure: ABORT
    commands:
      - echo "Build start at $(date)"
      - cd ${CODEBUILD_SRC_DIR}
      - echo "${COMPOSER_AUTH}" > auth.json
      - chmod +x bin/magento
      - composer install --optimize-autoloader --prefer-dist --no-dev
      - bin/magento setup:di:compile
      - composer dump-autoload --no-dev --optimize --apcu
      - bin/magento setup:static-content:deploy -f
      - echo "Build end at $(date)"
  post_build:
    on-failure: ABORT
    commands:
      - echo "Post Build start at $(date)"
      - echo "${CODEDEPLOY_APPSPEC}" > appspec.yml
      - echo "${MAGENTO_ENV}" > app/etc/env.php
      - echo "rm -rf --one-file-system --preserve-root" > cleanup.sh
      - |
        echo "if [ "\${DEPLOYMENT_GROUP_ID}" == "\${ADMIN_DEPLOYMENT_GROUP_ID}" ]; then
        bin/magento setup:db:status --no-ansi -n
        if [[ \$? -ne 0 ]]; then
        bin/magento setup:upgrade --keep-generated --no-ansi -n
        fi
        sudo cacheflush
        fi" > setup.sh
      - chmod +x cleanup.sh setup.sh
      - echo "Post Build end at $(date)"
artifacts:
    files:
      - '**/*'
    name: builds/${parameter["BRAND"]}/$(date +%Y-%m-%d)/${CODEBUILD_BUILD_NUMBER}/
